name: geopoint
author: synw <synwe@yahoo.com>
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/synw/geopoint
version: "0.2.3"

environment:
  sdk: ">=2.0.0 <3.0.0"
  
dependencies:
  meta: ^1.1.6
  latlong:
    git: https://github.com/DelmarZhao/dart-latlong.git
  slugify2: ^0.2.0

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.3
